# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "linzhanqi"
email = "linzhanqi123@gmail.com"
link = "https://github.com/mrhelloboy"
avatar = "/images/avatar.jpg"